trigger:
- master

resources:
  repositories:
    - repository: templates
      type: GitHub
      name: divvun/divvun-ci-config
      endpoint: divvun-ci

jobs:
  - template: repo/templates/keyboards.yml@templates
    parameters:
      name: smi
      packageName: keyboard-smi
      androidKeyAlias: sami_keyboard
      kbdgenFolder: "smi.kbdgen"
      repositoryWin: "https://pahkat.uit.no/repo/windows"
      repositoryMac: "https://pahkat.uit.no/repo/macos"
      languages:
        - projectjjName: giella-sme
          path: usr/share/giella/mobilespellers/se-mobile.zhfst
          name: se
        - projectjjName: giella-sma
          path: usr/share/giella/mobilespellers/sma-mobile.zhfst
          name: sma
        - projectjjName: giella-sms
          path: usr/share/giella/mobilespellers/sms-mobile.zhfst
          name: sms
        - projectjjName: giella-smn
          path: usr/share/giella/mobilespellers/smn-mobile.zhfst
          name: smn
        - projectjjName: giella-smj
          path: usr/share/giella/mobilespellers/smj-mobile.zhfst
          name: smj