resources:
  repositories:
    - repository: templates
      type: GitHub
      name: divvun/divvun-ci-config
      endpoint: divvun-ci

jobs:
  - template: repo/templates/keyboard-consolidated.yml@templates
    parameters:
      name: divvun
      packageName: keyboard-smi
      androidKeyAlias: sami_keyboard
      kbdgenFolder: "divvun.kbdgen"
      keyboardSources:
        - git: https://github.com/giellalt/keyboard-smi/
          branch: feature/new-format
          sourceKbdgen: smi.kbdgen
          layouts: [se, fi, nb, sv, sma, smj-NO, smj-SE, smn, sms]
        - git: https://github.com/giellalt/keyboard-crk/
          branch: master
          sourceKbdgen: crk.kbdgen
          layouts: [crk]
