internalName: sami_keyboard

locales:
  en:
    name: &bundleName "Sami Keyboards"
    description: "Mobile OS keyboards for the Sámi languages from the Divvun group at UiT."
  fi:
    name: "Saamen näppäimistöt"
    description: "Saamen kielen matkapuhelinnäppäimistöt Tromssan yliopiston Divvun-ryhmältä."
  nb:
    name: "Samiske tastaturer"
    description: "Mobiltastatur for samiske språk fra Divvun-gruppa ved UiT."
  se:
    name: "Sámi boallobeavddit"
    description: "Mobilboallobeavddit sámegielaide maid Divvun-joavku UiT:s lea ráhkadan."
  sv:
    name: "Samiska tangentbord"
    description: "Mobiltangentbord för samiska språk från Divvun-gruppen vid UiT."

author: The Divvun Group, UiT Norgga árktalaš universitehta
email: feedback@divvun.no

copyright: (c) 2017 Divvun/Giellatekno/UiT
organisation: UiT Norgga árktalaš universitehta

layouts: [sme, sma, smj_NO, smj_SE, smn, sms, sje, nob, swe, fin]

version: "1.1.2"
build: "18"

targets:
  android:
    packageId: no.uit.giella.keyboards.Sami
    icon: images/Sami-icon.png
    keyStore: $GTPRIV/admin/dev-accounts/dev_keys/sami_keyboard.keystore
    keyAlias: sami_keyboard

  ios:
    codeSignId: "Developer ID Installer: The University of Tromso (2K5J2584NX)"
    provisioningProfileId: "Gïelese distribution"
    packageId: no.uit.giella
    icon: images/Sami-icon.png
    bundleName: *bundleName
