internalName: __UND___keyboard

locales:
  en:
    name: &bundleName "__UNDEFINED__ Keyboards"
    description: "Mobile OS keyboards for the __UNDEFINED__ language from the Divvun group at UiT."
  nb:
    name: "__UNDEFINED__ tastatur"
    description: "Mobiltastatur for __UNDEFINED__ fra Divvun-gruppa."

author: The Divvun Group, UiT Norgga 치rktala코 universitehta
email: feedback@divvun.no

copyright: (c) 2017 Divvun/Giellatekno/UiT
organisation: UiT Norgga 치rktala코 universitehta

layouts: [__UND__]

version: 1.0
build: 1

targets:
  android:
    packageId: no.uit.giella.keyboards.__UND__
    icon: images/__UND__-icon.pdf
    keyStore: $GTPRIV/admin/dev-accounts/dev_keys/sami_keyboard.keystore
    keyAlias: sami_keyboard

  ios: &AppleID
    codeSignId: "Developer ID Installer: The University of Tromso (2K5J2584NX)"
    provisioningProfileId: Test
    packageId: no.uit.giella.keyboards.__UND__
    bundleName: *bundleName
    icon: images/__UND__-icon.png

  osx:
    <<: *AppleID
    icon: images/__UND__-keyboard-menu-icon.png
    version: 0.1.0
    resources: doc

  win:
    appName: *bundleName
    version: 0.1.0
    url: "http://divvun.no"
    uuid: "replace-with-real-uuid-one-for-each-language"
