internalName: sami_keyboard

locales:
  en:
    name: &bundleName "Sami Keyboards"
    description: "Mobile OS keyboards for the Sámi languages from the Divvun group at UiT."
  fi:
    name: "Saamen näppäimistöt"
    description: "Saamen kielen matkapuhelinnäppäimistöt Tromssan yliopiston Divvun-ryhmältä."
  nb:
    name: "Samiske tastaturer"
    description: "Mobiltastatur for samiske språk fra Divvun-gruppa ved UiT."
  nn:
    name: "Samiske tastatur"
    description: "Mobiltastatur for samiske språk frå Divvun-gruppa ved UiT."
  se:
    name: "Sámi boallobeavddit"
    description: "Mobilboallobeavddit sámegielaide maid Divvun-joavku UiT:s lea ráhkadan."
  sv:
    name: "Samiska tangentbord"
    description: "Mobiltangentbord för samiska språk från Divvun-gruppen vid UiT."

author: The Divvun Group, UiT Norgga árktalaš universitehta
email: feedback@divvun.no

copyright: (c) 2018 Divvun/Giellatekno/UiT
organisation: UiT Norgga árktalaš universitehta

layouts: [sme, sma, smj_NO, smj_SE, smn, sms, sje, nob, swe, fin]

version: "1.0"
build: "1"

targets:
  android:
    packageId: no.uit.giella.keyboards.Sami
    icon: images/Sami-icon.png
    keyStore: $GTPRIV/admin/dev-accounts/dev_keys/sami_keyboard.keystore
    keyAlias: sami_keyboard
    sentryDsn: "https://655b664788b4431eb9ad1b16c1fb38a6:70aa8ee35cbf46e7b1db726b59a2122e@sentry.io/213983"
    version: "1.2.2"
    build: "25"

  ios:
    codeSignId: "2K5J2584NX"
    provisioningProfileId: 'match Development no.uit.giella.keyboards.Sami'
    packageId: no.uit.giella.keyboards.Sami
    icon: images/Sami-icon.png
    bundleName: *bundleName
    aboutDir: aboutFiles
    sentryDsn: https://54df221153d64545b02ff3a98d616c83@sentry.io/1227106
    version: "1.2.2"
    build: "32"
