locales:
  en:
    name: "Sami Keyboards"
    description: "Keyboards for the Sámi languages from the Divvun group at UiT."
  fi:
    name: "Saamen näppäimistöt"
    description: "Saamen kielen näppäimistöt Tromssan yliopiston Divvun-ryhmältä."
  'no':
    name: "Samiske tastaturer"
    description: "Tastatur for samiske språk fra Divvun-gruppa ved UiT."
  nb:
    name: "Samiske tastaturer"
    description: "Tastatur for samiske språk fra Divvun-gruppa ved UiT."
  nn:
    name: "Samiske tastatur"
    description: "Tastatur for samiske språk frå Divvun-gruppa ved UiT."
  se:
    name: "Sámi boallobeavddit"
    description: "Boallobeavddit sámegielaide maid Divvun-joavku UiT:s lea ráhkadan."
  sv:
    name: "Samiska tangentbord"
    description: "Tangentbord för samiska språk från Divvun-gruppen vid UiT."

author: The Divvun Group, UiT Norgga árktalaš universitehta
email: feedback@divvun.no

copyright: (c) 2019 Divvun/Giellatekno/UiT
organisation: UiT Norgga árktalaš universitehta
