[bundle.mdf]
github = "giellalt/keyboard-mdf"
layouts = ["mdf"]

[bundle.myv]
github = "giellalt/keyboard-myv"
layouts = ["myv"]

[bundle.sms]
github = "giellalt/keyboard-sms"
layouts = ["sms"]

[bundle.smn]
github = "giellalt/keyboard-smn"
layouts = ["smn"]

[bundle.sma]
github = "giellalt/keyboard-sma"
layouts = ["sma"]

[bundle.sme]
github = "giellalt/keyboard-sme"
layouts = ["se"]

[bundle.smj]
github = "giellalt/keyboard-smj"
layouts = ["smj-NO", "smj-SE"]

