locales:
  en:
    name: "Divvun Keyboards"
    description: "Keyboards for minority and indigenous languages from the Divvun group at UiT."
  fi:
    name: "Divvun-näppäimistöt"
    description: "Vähemmistö- ja alkuperäiskielten kielten näppäimistöt Tromssan yliopiston Divvun-ryhmältä."
  'no':
    name: "Divvun-tastaturer"
    description: "Tastaturer for minoritets- og urfolksspråk fra Divvun-gruppa ved UiT."
  nb:
    name: "Divvun-tastaturer"
    description: "Tastaturer for minoritets- og urfolksspråk fra Divvun-gruppa ved UiT."
  nn:
    name: "Divvun-tastatur"
    description: "Tastatur for minoritets- og urfolksspråk frå Divvun-gruppa ved UiT."
  ru:
    name: "Клавиатуры Divvun"
    description: "Клавиатуры для языков меньшинств и коренных народов от группы Divvun в UiT."
  se:
    name: "Divvun-boallobeavddit"
    description: "Unnitlogu- ja eamiálbmotgielaid boallobeavddit maid Divvun-joavku UiT:s lea ráhkadan."
  smj:
    name: "Divvun-boallobievde"
    description: "Unneplågo- ja iemeálmmukgiela boallobievde majt Divvun-juogos UiT:an la dahkam."
  sv:
    name: "Divvun-tangentbord"
    description: "Tangentbord för minoritets- och urfolksspråk från Divvun-gruppen vid UiT."

author: The Divvun Group, UiT Norgga árktalaš universitehta
email: feedback@divvun.no

copyright: (c) 2015-2020 Divvun/Giellatekno/UiT
organisation: UiT Norgga árktalaš universitehta

dependencies:
  mdf:
    url: "giellalt/keyboard-mdf"
    layouts: ["mdf"]
  myv:
    url: "giellalt/keyboard-myv"
    layouts: ["myv"]
  sjd:
    url: "giellalt/keyboard-sjd"
    layouts: ["sjd"]
  sma:
    url: "giellalt/keyboard-sma"
    layouts: ["sma"]
  sme:
    url: "giellalt/keyboard-sme"
    layouts: ["se"]
  smj:
    url: "giellalt/keyboard-smj"
    layouts: ["smj-NO", "smj-SE"]
  smn:
    url: "giellalt/keyboard-smn"
    layouts: ["smn"]
  sms:
    url: "giellalt/keyboard-sms"
    layouts: ["sms"]
