[package]
name = "divvun"

[consolidated.sms]
git = "https://github.com/giellalt/keyboard-sms"
layouts = ["sms"]

[consolidated.smn]
git = "https://github.com/giellalt/keyboard-smn"
layouts = ["smn"]

[consolidated.sma]
git = "https://github.com/giellalt/keyboard-sma"
layouts = ["sma"]

[consolidated.smj]
git = "https://github.com/giellalt/keyboard-smj"
layouts = ["smj-NO", "smj-SE"]

[consolidated.sme]
git = "https://github.com/giellalt/keyboard-sme"
layouts = ["se"]

[consolidated.crk]
git = "https://github.com/giellalt/keyboard-crk/"
layouts = ["crk", "crk-Cans"]

[consolidated.srs]
git = "https://github.com/giellalt/keyboard-srs/"
layouts = ["srs"]

[bundles.keyboard_android]
[bundles.keyboard_ios]
