name: CI
on: [push, repository_dispatch]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - type: keyboard-ios
            os: [self-hosted, macos, aarch64]
          - type: keyboard-android
            os: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Divvun CI
        uses: divvun/actions/setup@master
        with:
          key: ${{ secrets.DIVVUN_KEY }}
      - name: Install build tools from Pahkat for macOS
        uses: divvun/actions/pahkat/init@master
        with:
          repo: https://pahkat.uit.no/devtools/
          channel: nightly
          packages: kbdgen
      - uses: actions/setup-java@v2
        name: Setup Java
        if: matrix.type == 'keyboard-android'
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Run kbdgen
        id: build
        uses: divvun/actions/keyboard/build-meta@master
        with:
          keyboard-type: ${{ matrix.type }}
          bundle-path: divvun.kbdgen
      - name: Publish (iOS)
        if: matrix.type == 'keyboard-ios' && github.ref == 'refs/heads/master'
        run: |
          source "$DIVVUN_CI_CONFIG/enc/env.sh"
          fastlane pilot upload --api_key_path "$DIVVUN_CI_CONFIG/enc/creds/macos/appstore-key.json" --skip_submission --skip_waiting_for_build_processing --ipa "output/ios-build/ipa/Divvun Keyboards.ipa"
        env:
          SPACESHIP_SKIP_2FA_UPGRADE: 1
          LANG: en_US.UTF-8
      - uses: actions/upload-artifact@v2
        if: matrix.type == 'keyboard-android' && github.ref == 'refs/heads/master'
        with:
          name: android
          path: output/*.apk
      - name: Publish (Android)
        if: matrix.type == 'keyboard-android' && github.ref == 'refs/heads/master'
        run: |
          source "$DIVVUN_CI_CONFIG/enc/env.sh"
          cd output/deps/giella-ime
          ./gradlew publishApk


