name: CI
on: [push, repository_dispatch]
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Setup Divvun CI
        uses: divvun/actions/setup@develop
        with:
          key: ${{ secrets.DIVVUN_KEY }}
      - name: Install build tools from Pahkat for macOS
        uses: divvun/actions/pahkat/init@develop
        with:
          repo: https://pahkat.uit.no/devtools/
          channel: nightly
          packages: kbdgen
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
      - name: Install Dependencies (iOS) 
        run: |
          sudo gem install fastlane
          rustup component add rustfmt
          rustup target add aarch64-apple-ios
          rustup target add x86_64-apple-ios
          cargo install cargo-lipo
      - name: Run kbdgen
        id: build
        uses: divvun/actions/keyboard/build-meta@develop
        with:
          keyboard-type: keyboard-ios
          bundle-path: divvun.kbdgen
      - name: Publish (iOS)
        run: |
          source "$DIVVUN_CI_CONFIG/enc/env.sh"
          fastlane pilot upload --skip_submission --skip_waiting_for_build_processing --ipa output/ios-build/ipa/HostingApp.ipa
